### Setup

In [1]:
import numpy as np
import choix
from scipy.optimize import minimize
import scipy.stats as stats
import matplotlib.pyplot as plt
import random
from matplotlib import colors
import pandas as pd
import seaborn as sns
import pickle
import os
import sys


sys.path.append(os.path.abspath('../../'))
from metrics import compute_acc, compute_weighted_acc
from opt_fair import *

In [2]:
!nvidia-smi

Tue Dec 16 11:30:52 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.5     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          Off | 00000000:17:00.0 Off |                    0 |
| N/A   59C    P0              73W / 300W |  20589MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+--

In [3]:
import os
import torch
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [4]:
print(f"Current PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA version: {torch.version.cuda}")

Current PyTorch version: 2.9.1+cu128
CUDA available: True
CUDA version: 12.8


In [5]:
with open("data/FaceAgePC.pickle", 'rb') as handle:
    PC_faceage = pickle.load(handle)    
with open("data/FaceAgeDF.pickle", 'rb') as handle:
    df_faceage = pickle.load(handle)

In [6]:
df_faceage

,full_path,score,gender
0,nm1442940_rm3965098752_1996-10-3_2006.jpg,10,0.0
1,nm4832920_rm1781768448_2003-8-28_2013.jpg,10,0.0
2,nm0652089_rm860657920_1992-3-10_2002.jpg,10,0.0
3,nm0004917_rm1493730304_1969-5-12_1979.jpg,10,0.0
4,nm1113550_rm1332711936_1996-4-14_2006.jpg,10,0.0
...,...,...,...
9145,475367_1941-08-03_2011.jpg,70,1.0
9146,304085_1919-07-07_1989.jpg,70,1.0
9147,nm0001627_rm4164078592_1927-2-20_1997.jpg,70,1.0
9148,nm0000024_rm1715129344_1904-4-14_1974.jpg,70,1.0


In [7]:
import opt_fair
all_pc_faceage  = opt_fair._pc_without_reviewers(PC_faceage)

size = len(df_faceage)
print(size)
classes = [0]*size

9150


In [8]:
print(len(all_pc_faceage))

250249


### PG EM

In [9]:
import random
from pgem import EMWrapper

max_iter = 500
pg = EMWrapper(PC_faceage, max_iter, device, 44)
r_est, beta_est, ll = pg.run_algorithm()

cuda
[[5048 2757 3897]
 [8759  803 1496]
 [ 666 6292 3779]
 [8704  528 3445]
 [7667 5961 1634]]
Device: cuda
Initial Log-likelihood: -0.770476


PG-EM Optimization:   0%|                   | 1/500 [00:00<03:52,  2.14it/s]

Iter 000: Log-likelihood = -0.469346


PG-EM Optimization:   2%|▎                  | 8/500 [00:02<02:40,  3.07it/s]

Converged at iter 8, Log-likelihood change = 5.224319e-07


In [10]:
print(ll)

-0.4557802863613141


In [11]:
stats.kendalltau(-1*r_est, df_faceage['score'])

SignificanceResult(statistic=0.5754607538571679, pvalue=0.0)

In [12]:
print(compute_acc(df_faceage, 1*r_est, device))

0.20989763736724854


/workspace/main/metrics.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  s = torch.tensor(predicted_scores, dtype=torch.float32, device=device)


In [13]:
print(compute_weighted_acc(df_faceage, 1*r_est, device))

0.1279328167438507


/workspace/main/metrics.py:50: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  s = torch.tensor(predicted_scores,


### BT

In [14]:
%%time
bt_scores = choix.opt_pairwise(size, all_pc_faceage, alpha=0, method='Newton-CG', initial_params=None, max_iter=None, tol=1e-05)

CPU times: user 10min 26s, sys: 3min 35s, total: 14min 1s
Wall time: 2min 1s


In [15]:
stats.kendalltau(bt_scores, df_faceage['score'])

SignificanceResult(statistic=0.575393885555222, pvalue=0.0)

In [16]:
print(compute_acc(df_faceage, bt_scores, device))

0.7900686264038086


In [17]:
print(compute_weighted_acc(df_faceage, bt_scores, device))

0.8719564080238342


### BARP

In [18]:
# classes = [0]
FaceAge = opt_fair.BARP(data = PC_faceage, penalty = 0, classes = classes, device=device)

In [19]:
crowd_labels = pd.read_csv('data/crowd_labels.csv')
num_reviewers =  crowd_labels['performer'].nunique()

In [ ]:
%%time
annot_bt_temp, annot_bias =  opt_fair._alternate_optim_torch(size, num_reviewers, FaceAge, iters = 100)

 67%|█████████████████████████▍            | 67/100 [05:17<02:50,  5.18s/it]

In [ ]:
stats.kendalltau(annot_bt_temp.cpu(), df_faceage['score'])

In [ ]:
# import warnings
# warnings.filterwarnings('ignore')
print(compute_acc(df_faceage, annot_bt_temp.cpu(), device))

In [ ]:
print(compute_weighted_acc(df_faceage, annot_bt_temp.cpu(), device))

### RC

In [ ]:
%%time

rc_obj = RankCentrality(device)
A = rc_obj.matrix_of_comparisons(size, all_pc_faceage)
# print("A matrix done")
P = rc_obj.trans_prob(A)
# print("P matrix done")
pi = rc_obj.stationary_dist(P)
rank_centrality_scores = torch.log(pi).cpu().numpy()

In [ ]:
stats.kendalltau(rank_centrality_scores, df_faceage['score'])

In [ ]:
print(compute_acc(df_faceage, rank_centrality_scores, device))

In [ ]:
print(compute_weighted_acc(df_faceage, rank_centrality_scores, device))

### FactorBT

In [ ]:
%%time

factorbt_test = FactorBT(data = PC_faceage, penalty = 0, classes = classes, device=device)
factorbt_scores,y,z = factorbt_test.alternate_optim(iters=100)

In [ ]:
stats.kendalltau(factorbt_scores.cpu(), df_faceage['score'])

In [ ]:
print(compute_acc(df_faceage, factorbt_scores.cpu(), device))

In [ ]:
print(compute_weighted_acc(df_faceage, factorbt_scores.cpu(), device))

### CrowdBT

In [ ]:
%%time

crowdbt_test = CrowdBT(data = PC_faceage, penalty = 0, device=device)
crowdbt_scores, _ = crowdbt_test.alternate_optim(size, len(PC_faceage))

In [ ]:
print(crowdbt_scores)

In [ ]:
stats.kendalltau(crowdbt_scores.cpu(), df_faceage['score'])

In [ ]:
print(compute_acc(df_faceage, crowdbt_scores, device))

In [ ]:
print(compute_weighted_acc(df_faceage, crowdbt_scores, device))