### Setup

In [1]:
import numpy as np
import choix
from scipy.optimize import minimize
import scipy.stats as stats
import matplotlib.pyplot as plt
import random
from matplotlib import colors
import pandas as pd
import seaborn as sns
import pickle
import os
import sys


sys.path.append(os.path.abspath('../../'))
from metrics import compute_acc, compute_weighted_acc
from opt_fair import *

In [2]:
!nvidia-smi

Tue Dec 16 11:34:03 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.5     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          Off | 00000000:17:00.0 Off |                    0 |
| N/A   59C    P0              75W / 300W |  23977MiB / 81920MiB |     20%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+--

In [3]:
import os
import torch
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [4]:
print(f"Current PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA version: {torch.version.cuda}")

Current PyTorch version: 2.9.1+cu128
CUDA available: True
CUDA version: 12.8


In [5]:
with open("data/PassagePC.pickle", 'rb') as handle:
    PC_faceage = pickle.load(handle)    
with open("data/PassageDF.pickle", 'rb') as handle:
    df_faceage = pickle.load(handle)

In [6]:
df_faceage

,label,score
0,"a star. Our planet, Earth, orbits, or circles,...",1
1,"Adam, We did not have plastic toys. I played w...",1
2,Who said the little owl. Who wants to hunt wit...,1
3,dead leaf. This is a mole. Moles burrow underg...,1
4,ereaddatagradepsenvironcomp.html Environment r...,1
...,...,...
467,work over the summer on any changes they wish ...,12
468,between January and December plunged the Unite...,12
469,into a newly opened bank account. I was amazed...,12
470,"occurring phenomenon, manmade by products are ...",12


In [7]:
import opt_fair
all_pc_faceage  = opt_fair._pc_without_reviewers(PC_faceage)

size = len(df_faceage)
print(size)
classes = [0]*size

472


In [8]:
print(len(all_pc_faceage))

11763


### PG EM

In [9]:
import random
from pgem import EMWrapper

max_iter = 500
pg = EMWrapper(PC_faceage, max_iter, device, 44)
r_est, beta_est, ll = pg.run_algorithm()

cuda
[[272 348 283]
 [415 354  33]
 [465 311 144]
 [ 49  85  54]
 [415  20 331]]
Device: cuda
Initial Log-likelihood: -0.767009


PG-EM Optimization:   0%|                   | 1/500 [00:00<01:35,  5.22it/s]

Iter 000: Log-likelihood = -0.562702


PG-EM Optimization:   2%|▎                  | 8/500 [00:00<00:27, 17.96it/s]

Converged at iter 8, Log-likelihood change = 3.474900e-07


In [10]:
print(ll)

-0.523413492401323


In [11]:
stats.kendalltau(-1*r_est, df_faceage['score'])

SignificanceResult(statistic=-0.3686092224138372, pvalue=5.1935725002558044e-30)

In [12]:
print(compute_acc(df_faceage, 1*r_est, device))

0.695236086845398


/workspace/main/metrics.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  s = torch.tensor(predicted_scores, dtype=torch.float32, device=device)


In [13]:
print(compute_weighted_acc(df_faceage, 1*r_est, device))

0.7565375566482544


/workspace/main/metrics.py:50: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  s = torch.tensor(predicted_scores,


### BT

In [14]:
%%time
bt_scores = choix.opt_pairwise(size, all_pc_faceage, alpha=0, method='Newton-CG', initial_params=None, max_iter=None, tol=1e-05)

CPU times: user 47.5 s, sys: 2min 20s, total: 3min 7s
Wall time: 7.55 s


In [15]:
stats.kendalltau(bt_scores, df_faceage['score'])

SignificanceResult(statistic=0.3408721163582005, pvalue=6.657069444052687e-26)

In [16]:
print(compute_acc(df_faceage, bt_scores, device))

0.6804668307304382


In [17]:
print(compute_weighted_acc(df_faceage, bt_scores, device))

0.74333256483078


### BARP

In [18]:
# classes = [0]
FaceAge = opt_fair.BARP(data = PC_faceage, penalty = 0, classes = classes, device=device)

In [19]:
crowd_labels = pd.read_csv('data/passage_cleaned.csv')
num_reviewers =  crowd_labels['performer'].nunique()

In [20]:
%%time
annot_bt_temp, annot_bias =  opt_fair._alternate_optim_torch(size, num_reviewers, FaceAge, iters = 100)

100%|█████████████████████████████████████| 100/100 [01:14<00:00,  1.33it/s]

CPU times: user 56.5 s, sys: 19.7 s, total: 1min 16s
Wall time: 1min 16s


In [21]:
stats.kendalltau(annot_bt_temp.cpu(), df_faceage['score'])

SignificanceResult(statistic=0.36267695314604337, pvalue=4.1801087627048257e-29)

In [22]:
# import warnings
# warnings.filterwarnings('ignore')
print(compute_acc(df_faceage, annot_bt_temp.cpu(), device))

0.6920762658119202


/workspace/main/metrics.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  s = torch.tensor(predicted_scores, dtype=torch.float32, device=device)


In [23]:
print(compute_weighted_acc(df_faceage, annot_bt_temp.cpu(), device))

0.7587689757347107


/workspace/main/metrics.py:50: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  s = torch.tensor(predicted_scores,


### RC

In [24]:
%%time

rc_obj = RankCentrality(device)
A = rc_obj.matrix_of_comparisons(size, all_pc_faceage)
# print("A matrix done")
P = rc_obj.trans_prob(A)
# print("P matrix done")
pi = rc_obj.stationary_dist(P)
rank_centrality_scores = torch.log(pi).cpu().numpy()

CPU times: user 61.3 ms, sys: 53.5 ms, total: 115 ms
Wall time: 112 ms


In [25]:
stats.kendalltau(rank_centrality_scores, df_faceage['score'])

SignificanceResult(statistic=0.2891796316210329, pvalue=4.669770558223192e-19)

In [26]:
print(compute_acc(df_faceage, rank_centrality_scores, device))

0.6521800756454468


In [27]:
print(compute_weighted_acc(df_faceage, rank_centrality_scores, device))

0.71303790807724


### FactorBT

In [28]:
%%time

factorbt_test = FactorBT(data = PC_faceage, penalty = 0, classes = classes, device=device)
factorbt_scores,y,z = factorbt_test.alternate_optim(iters=100)

100%|█████████████████████████████████████| 100/100 [01:58<00:00,  1.18s/it]

CPU times: user 1min 36s, sys: 21.8 s, total: 1min 58s
Wall time: 1min 58s


In [29]:
stats.kendalltau(factorbt_scores.cpu(), df_faceage['score'])

SignificanceResult(statistic=0.3853247676997512, pvalue=1.223645231494805e-32)

In [30]:
print(compute_acc(df_faceage, factorbt_scores.cpu(), device))

0.7040895819664001


In [31]:
print(compute_weighted_acc(df_faceage, factorbt_scores.cpu(), device))

0.7693222761154175


### CrowdBT

In [32]:
%%time

crowdbt_test = CrowdBT(data = PC_faceage, penalty = 0, device=device)
crowdbt_scores, _ = crowdbt_test.alternate_optim(size, len(PC_faceage))

init done


100%|█████████████████████████████████████| 100/100 [01:31<00:00,  1.09it/s]

CPU times: user 1min 15s, sys: 15.9 s, total: 1min 31s
Wall time: 1min 31s


In [33]:
print(crowdbt_scores)

tensor([-6.7402e-01, -2.2106e+00, -1.5958e+00, -2.6131e-01, -3.5033e-01,
        -2.4535e+00, -9.3857e-01, -1.4554e+00, -2.8487e+00, -1.6854e+00,
        -1.6540e+00, -1.2707e+00, -5.6968e-01, -1.2141e+00, -2.8755e+00,
        -1.1133e+00, -2.0250e+00, -4.0469e-01, -5.3687e-01, -8.7550e-01,
        -7.4703e-01, -7.5716e-01, -5.3233e-01, -1.5521e+00,  2.7524e-01,
        -2.2295e+00, -1.2040e+00, -4.1375e-01,  6.2200e-02, -2.2452e+00,
        -2.5347e+00, -1.4764e+00, -1.1584e+00, -1.3891e+00, -1.6996e+00,
        -2.1102e+00, -1.4289e+00, -1.9378e-01, -1.6917e+00, -3.4371e-01,
        -2.5352e+00, -1.8017e+00, -2.5048e+00, -1.0631e+00, -2.7833e+00,
        -2.6681e-01, -1.5468e+00,  5.5271e-01, -1.9460e+00, -1.4887e+00,
        -1.5509e-01, -6.6632e-02, -1.8898e+00, -1.3615e+00,  2.6951e-01,
        -1.5435e+00, -2.1985e+00, -9.4731e-01,  8.7842e-01, -2.0163e+00,
        -9.1580e-01, -4.6960e-01, -1.1661e+00, -1.0308e+00,  2.3423e+00,
        -2.5304e+00, -1.5619e+00, -3.4359e+00,  5.9

In [34]:
stats.kendalltau(crowdbt_scores.cpu(), df_faceage['score'])

SignificanceResult(statistic=0.386639901821448, pvalue=7.516780087725139e-33)

In [35]:
print(compute_acc(df_faceage, crowdbt_scores, device))

0.7047861218452454


In [36]:
print(compute_weighted_acc(df_faceage, crowdbt_scores, device))

0.7693936228752136
